'\" t
.\"     Title: krgadm
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/29/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "KRGADM" "1" "01/29/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
krgadm \- Start, stop or get status of a Kerrighed cluster
.SH "SYNOPSIS"
.HP \w'\fBkrgadm\fR\ 'u
\fBkrgadm\fR [\-h | \-\-help]
.HP \w'\fBkrgadm\fR\ 'u
\fBkrgadm\fR cluster {status | wait_start | poweroff | reboot}
.HP \w'\fBkrgadm\fR\ 'u
\fBkrgadm\fR cluster {start} [\-n | \-\-nodes] [\-a | \-\-auto]
.HP \w'\fBkrgadm\fR\ 'u
\fBkrgadm\fR nodes
.SH "DESCRIPTION"
.PP

\fBkrgadm\fR
allows the user to start, stop or get status of a Kerrighed cluster\&.\&.
.PP
Each
\fBkrgadm\fR
invocation is followed by a command and some options relative to this mode\&.
.PP
cluster
.RS 4
Start, stop or see the cluster status\&.
.RE
.PP
nodes
.RS 4
Get cluster nodes status\&.
.RE
.SH "GENERAL OPTIONS"
.PP
.PP
\-h, \-\-help
.RS 4
Print help and exit
.RE
.SH "MODES"
.PP
.PP
cluster
.RS 4
Manage the cluster
.RE
.PP
nodes
.RS 4
Prints cluster nodes status
.RE
.SH "CLUSTER COMMANDS"
.PP
.PP
start
.RS 4
Start the cluster (see CLUSTER START OPTIONS below)
.RE
.PP
status
.RS 4
Print cluster status
.RE
.PP
wait_start
.RS 4
Return once cluster is started
.RE
.PP
poweroff
.RS 4
Power off all nodes belonging to the cluster
.RE
.PP
reboot
.RS 4
Reboot all nodes belonging to the cluster
.RE
.SH "CLUSTER START OPTIONS"
.PP
By default,
\fBkrgadm cluster start\fR
start the cluster with available nodes\&.
.PP
.PP
\-n, \-\-nodes
.RS 4
Wait for a given list of nodes before starting\&. List of nodes is of the form: 1,3,7,10\-12,43\-46
.RE
.PP
\-n, \-\-nodes
.RS 4
Wait for the given number of nodes to be present before starting\&.
.RE
.SH "AUTHOR"
.PP
Renaud Lottiaux
renaud\&.lottiaux@kerlabs\&.com
.PP
Jean Parpaillon
jean\&.parpaillon@kerlabs\&.com
